### ISSUE TITLE
Store data generated from circuit compilation in remote storage

### ISSUE THREAD

**Issue by magestrio** [orochi-network/zkDatabase#55]
o1js offers the capability to cache data generated from zkApp and zkProgram. Storing this data externally is a beneficial strategy. It will considerably enhance the circuit compilation time, thereby improving the user experience.
```ts
const cache = Cache.FileSystem(`/name`)
SmartContract.compile({cache})
```

**Comment by chiro-hiro** [comment]
Can this support in memory caching?

**Comment by magestrio** [comment]
> Can this support in memory caching?

Yeap, we can write directly to the directory provided by oj1s.

```ts
Cache.FileSystem(`/name`).write(UInt8Array)
```

**Comment by chiro-hiro** [comment]
> > Can this support in memory caching?
> 
> 
> 
> Yeap, we can write directly to the directory provided by oj1s.
> 
> 
> 
> ```ts
> 
> Cache.FileSystem(`/name`).write(UInt8Array)
> 
> ```

I meant memory not storage 🥲
